
from ..utils.customobjs import objdict as odict

carelink_parse_kw = odict({
    "kwargs": odict({
      "index_col": "DateTime",
      "parse_dates": True,
      "low_memory": False
    }),
    "dtypes": odict({
      "original": {
        "New Device Time": "datetime64[ns]",
        "BG Reading (mg/dL)": "Sparse[float]",
        "Linked BG Meter ID": "Sparse[float]",
        "Basal Rate (U/h)": "float",
        "Temp Basal Amount": "Sparse[float]",
        "Temp Basal Type": "string",
        "Temp Basal Duration (h:mm:ss)": "Sparse[string]",
        "Bolus Type": "category",
        "Bolus Volume Selected (U)": "float",
        "Bolus Volume Delivered (U)": "float",
        "Bolus Duration (h:mm:ss)": "Sparse[string]",
        "Prime Type": "category",
        "Prime Volume Delivered (U)": "Sparse[float]",
        "Alarm": "category",
        "Suspend": "category",
        "Rewind": "category",
        "BWZ Estimate (U)": "Sparse[float]",
        "BWZ Target High BG (mg/dL)": "Sparse[float]",
        "BWZ Target Low BG (mg/dL)": "Sparse[float]",
        "BWZ Carb Ratio (g/U)": "Sparse[float]",
        "BWZ Insulin Sensitivity (mg/dL/U)": "Sparse[float]",
        "BWZ Carb Input (grams)": "Sparse[float]",
        "BWZ BG Input (mg/dL)": "Sparse[float]",
        "BWZ Correction Estimate (U)": "Sparse[float]",
        "BWZ Food Estimate (U)": "Sparse[float]",
        "BWZ Active Insulin (U)": "Sparse[float]",
        "BWZ Status": "category",
        "Sensor Calibration BG (mg/dL)": "Sparse[float]",
        "Sensor Glucose (mg/dL)": "float",
        "ISIG Value": "float",
        "Event Marker": "Sparse[string]",
        "Bolus Number": "Sparse[float]",
        "Bolus Cancellation Reason": "category",
        "BWZ Unabsorbed Insulin Total (U)": "Sparse[float]",
        "Final Bolus Estimate": "Sparse[float]",
        "Scroll Step Size": "category",
        "Insulin Action Curve Time": "Sparse[float]",
        "Sensor Calibration Rejected Reason": "category",
        "Preset Bolus": "Sparse[float]",
        "Bolus Source": "category",
        "Network Device Associated Reason": "category",
        "Network Device Disassociated Reason": "category",
        "Network Device Disconnected Reason": "category",
        "Sensor Exception": "category",
        "Preset Temp Basal Name": "category"
      },
      "no_sparse": {
        "New Device Time": "datetime64[ns]",
        "BG Reading (mg/dL)": "float",
        "Linked BG Meter ID": "float",
        "Basal Rate (U/h)": "float",
        "Temp Basal Amount": "float",
        "Temp Basal Type": "category",
        "Temp Basal Duration (h:mm:ss)": "string",
        "Bolus Type": "category",
        "Bolus Volume Selected (U)": "float",
        "Bolus Volume Delivered (U)": "float",
        "Bolus Duration (h:mm:ss)": "string",
        "Prime Type": "category",
        "Prime Volume Delivered (U)": "float",
        "Alarm": "category",
        "Suspend": "category",
        "Rewind": "category",
        "BWZ Estimate (U)": "float",
        "BWZ Target High BG (mg/dL)": "float",
        "BWZ Target Low BG (mg/dL)": "float",
        "BWZ Carb Ratio (g/U)": "float",
        "BWZ Insulin Sensitivity (mg/dL/U)": "float",
        "BWZ Carb Input (grams)": "float",
        "BWZ BG Input (mg/dL)": "float",
        "BWZ Correction Estimate (U)": "float",
        "BWZ Food Estimate (U)": "float",
        "BWZ Active Insulin (U)": "float",
        "BWZ Status": "category",
        "Sensor Calibration BG (mg/dL)": "float",
        "Sensor Glucose (mg/dL)": "float",
        "ISIG Value": "float",
        "Event Marker": "category",
        "Bolus Number": "float",
        "Bolus Cancellation Reason": "category",
        "BWZ Unabsorbed Insulin Total (U)": "float",
        "Final Bolus Estimate": "float",
        "Scroll Step Size": "category",
        "Insulin Action Curve Time": "float",
        "Sensor Calibration Rejected Reason": "category",
        "Preset Bolus": "float",
        "Bolus Source": "category",
        "Network Device Associated Reason": "category",
        "Network Device Disassociated Reason": "category",
        "Network Device Disconnected Reason": "category",
        "Sensor Exception": "category",
        "Preset Temp Basal Name": "category"
      },
      "added": {
        "d1w5": "float",
        "Sd1w5": "float",
        "hour": "int",
        "minute": "int",
        "x(t)": "float",
        "y(t)": "float"
      }
    }),
    "timedelta": odict({
      "cols": [
        "Temp Basal Duration (h:mm:ss)",
        "Bolus Duration (h:mm:ss)"
      ]
    })
  })
